<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [],
    ],
];


// Too few arguments to function Announcements\Handler\AnnouncementsReadHandler::__construct(), 0 
// passed in /var/www/vendor/zendframework/zend-expressive/src/MiddlewareContainer.php on line 64 and exactly 4 expected
